# Generated by Django 4.2.6 on 2023-11-03 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_on"]},
        ),
    ]
