# Generated by Django 4.2.6 on 2023-11-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="base.addresses",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered",
            field=models.IntegerField(default=0),
        ),
    ]
