# Generated by Django 4.2.6 on 2023-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_customer_deliverer_owner_user_name_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
