# Generated by Django 4.2.6 on 2023-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresses",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customerdelivererrelationship",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerdelivererrelationship",
            name="deliverer",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="delivererprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="phonenumbers",
            name="user",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Deliverer",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.DeleteModel(
            name="Addresses",
        ),
        migrations.DeleteModel(
            name="CustomerDelivererRelationship",
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
        migrations.DeleteModel(
            name="DelivererProfile",
        ),
        migrations.DeleteModel(
            name="Items",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="PhoneNumbers",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
