# Generated by Django 4.2.6 on 2023-11-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_order_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
