# Generated by Django 4.2.6 on 2023-11-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.deliverer'),
        ),
    ]
